// Code generated by tools/codegen-reasons from reasons.yaml. DO NOT EDIT.

package reasons

var (
{{- range $condition, $reasons := .Conditions }}

    // reasons for the {{$condition}} condition.
{{ range $reasonName, $reason := $reasons }}
    {{$reasonName}} = ReasonMeta{
        template:        "{{$reason.Template}}",
        defaultSeverity: "{{$reason.DefaultSeverity}}",
        component:       "{{$reason.Component}}",
    }
{{- end -}}
{{- end -}}
)

// byName maps reason identifiers, as declared in reasons.yaml, to their
// metadata. It backs the ByName lookup used to validate configuration that
// references reasons by name.
var byName = map[string]ReasonMeta{
{{- range $condition, $reasons := .Conditions }}
{{- range $reasonName, $reason := $reasons }}
    "{{$reasonName}}": {{$reasonName}},
{{- end -}}
{{- end }}
}

// components is the distinct set of event-budget components declared in
// reasons.yaml. Together with the platform-reserved slots it is bounded by
// the capacity ledger in tools/codegen-reasons.
var components = map[string]struct{}{
{{- range $component := .Components }}
    "{{$component}}": {},
{{- end }}
}

// MaxComponents is N, the declared platform capacity for event-budget
// components, mirrored from the capacity ledger in tools/codegen-reasons.
// The node-global event ceiling is derived as N times the per-component
// quota and must never be tuned independently.
const MaxComponents = {{ .MaxComponents }}
